package schema

import (
	"fmt"
	"path/filepath"

	"github.com/wandering-compiler/w17ctl/internal/core"
	"github.com/wandering-compiler/w17ctl/internal/plan"
	"github.com/wandering-compiler/w17ctl/internal/protoscan"
	"github.com/wandering-compiler/w17ctl/internal/schema"
	"github.com/wandering-compiler/w17ctl/internal/vocab"
	codegenpb "github.com/wandering-compiler/sdk/go/pb/w17compiler"
	"github.com/wandering-compiler/sdk/go/tooling/migrate"
)

// RenderCmd writes the full-create dev plan for the project's current models.
//
// From EMPTY state, deliberately: this artefact is what a database that does
// not exist yet is built from, and the dev path RECONCILES rather than walks a
// history — the planner diffs what the models say against what the store
// holds, so a plan built from empty applies cleanly to an empty store and is
// re-rendered whole whenever the models change. That is the same thing
// `db/init/<domain>/01_schema.sql` was, and it is generated by the same
// planner; what changes is that a step in the stack runs it every time the
// stack comes up, instead of the postgres entrypoint running it only on a
// volume that has never existed before.
type RenderCmd struct {
	Protos  []string `name:"proto" short:"p" placeholder:"PROTO" help:"Path to a .proto schema. Repeatable. Optional — omitted, the model protos are discovered under the lock's proto dir, the same way 'stack build' finds them."`
	Imports []string `name:"import" short:"I" placeholder:"DIR" help:"Additional proto import path. Repeatable."`
	Out     string   `name:"out" placeholder:"DIR" default:"w17/schema" help:"Where the rendered plan goes. This is the directory '<binary> schema apply --schema' defaults to."`
	Console string   `name:"console" placeholder:"HOST:PORT" env:"W17_CONSOLE_ADDR" help:"gRPC endpoint of the console. Optional — falls back to the console you are logged into (w17ctl login), then the binary's compile-time default."`
}

func (c *RenderCmd) Run() error {
	protos, imports, cleanup, err := c.resolveProtos()
	if err != nil {
		return err
	}
	defer cleanup()
	if len(protos) == 0 {
		return fmt.Errorf(
			"schema render: no model protos found under %s\n"+
				"  why: an empty file set plans an empty schema, and an empty plan is a\n"+
				"       database with no tables that reports success\n"+
				"  fix: pass --proto explicitly, or run this from the project root",
			c.protoDir())
	}

	ctx, cancel := core.ClientCtx()
	defer cancel()
	ir, err := schema.LoadIRBytes(ctx, protos, imports, c.Console)
	if err != nil {
		return fmt.Errorf("schema render: load schema: %w", err)
	}
	// Empty base = the full create.
	p, err := plan.PlanMigration(nil, ir, c.baselines())
	if err != nil {
		return fmt.Errorf("schema render: %w", err)
	}
	if len(p.GetMigrations()) == 0 {
		return fmt.Errorf(
			"schema render: the planner returned nothing for %d proto file(s)\n"+
				"  why: a project with tables plans a full create from empty state; an empty\n"+
				"       plan here would be written down and later applied as success",
			len(protos))
	}
	if err := migrate.WriteDevPlan(c.Out, p); err != nil {
		return fmt.Errorf("schema render: %w", err)
	}
	// The same plan, as readable DDL. Written from the same value by the same
	// step so the two cannot drift.
	if err := migrate.WriteDevPlanDDL(c.Out, p); err != nil {
		return fmt.Errorf("schema render: %w", err)
	}
	for _, m := range p.GetMigrations() {
		fmt.Fprintf(core.Stdout, "schema render: %s — %d byte(s) of DDL\n", m.GetConnection(), len(m.GetUpSql()))
	}
	fmt.Fprintf(core.Stdout, "schema render: %d connection(s) → %s\n", len(p.GetMigrations()), c.Out)
	return nil
}

// resolveProtos mirrors `fixtures render`: an explicit --proto when given,
// otherwise the model protos under the lock's proto dir, found by the same
// package `stack build` uses.
func (c *RenderCmd) resolveProtos() (protos, imports []string, cleanup func(), err error) {
	cleanup = func() {}
	if len(c.Protos) > 0 {
		return c.Protos, c.Imports, cleanup, nil
	}
	root, err := core.FindProjectRoot()
	if err != nil {
		return nil, nil, cleanup, fmt.Errorf("schema render: %w", err)
	}
	base := filepath.Join(root, c.protoDir())
	models, modules, err := protoscan.DiscoverModelProtos(base)
	if err != nil {
		return nil, nil, cleanup, fmt.Errorf("schema render: discover model protos: %w", err)
	}
	if len(models) == 0 {
		return nil, nil, cleanup, nil
	}
	models = append(models, modules...)
	vocabDir, vcleanup, err := vocab.ExtractW17Vocab()
	if err != nil {
		return nil, nil, cleanup, fmt.Errorf("schema render: stage w17 vocab: %w", err)
	}
	return models, append([]string{base, vocabDir}, c.Imports...), vcleanup, nil
}

// protoDir is the project's proto root, from the console's lock projection.
func (c *RenderCmd) protoDir() string {
	if view := core.DescribeLockBestEffort(c.Console); view != nil && view.GetProtoDir() != "" {
		return view.GetProtoDir()
	}
	return "proto"
}

// baselines copies each connection's ledger pin off the lock.
//
// Off the LOCK specifically, because that is the same file the deploy gate
// reads when it decides whether the database is behind the code. One source
// means the row this artefact writes and the row that gate looks for cannot
// name different migrations — which they would the moment either side derived
// the id for itself.
//
// A missing or unreadable lock yields NO pins rather than an error. Rendering
// the schema is useful before a project has ever been pushed (that is how a
// project gets its first schema), and the connections in such a lock have no
// `target_migration_id` to record anyway. The artefact then carries an empty
// baseline_sql, and `schema apply` builds the schema and records nothing —
// exactly the state that existed before baselines were written at all.
func (c *RenderCmd) baselines() []*codegenpb.PlanBaseline {
	root, err := core.FindProjectRoot()
	if err != nil {
		return nil
	}
	lk, err := migrate.LoadLockView(filepath.Join(root, "w17", "lock.yaml"))
	if err != nil {
		return nil
	}
	out := make([]*codegenpb.PlanBaseline, 0, len(lk.Connections))
	for _, conn := range lk.Connections {
		out = append(out, &codegenpb.PlanBaseline{
			Connection:    conn.Name,
			MigrationId:   conn.TargetMigrationID,
			ContentSha256: conn.TargetContentSha256,
		})
	}
	return out
}
