// Code generated by scripts/publish-w17ctl.sh — DO NOT EDIT.
//
// The sdk/go snapshot the published sdk repo held when this client was
// published — derived from that repo's HEAD commit, NOT from the proxy's
// `@latest`, which lags a fresh publish by minutes. core.SdkFloor documents
// what the floor is for and what it cannot catch.

package core

func init() { SdkFloor = "v0.1.0-rc.5" }
