// Code generated by scripts/publish-w17ctl.sh — DO NOT EDIT.
//
// The sdk/go snapshot the published sdk repo held when this client was
// published — derived from that repo's HEAD commit, NOT from the proxy's
// `@latest`, which lags a fresh publish by minutes. core.SdkFloor documents
// what the floor is for and what it cannot catch.

package core

func init() { SdkFloor = "v0.0.0-20261001002917-af0ac524f804" }
