package migrate

import (
	"fmt"
	"os"
	"strings"

	"github.com/wandering-compiler/w17ctl/internal/lockfile"
	migratesdk "github.com/wandering-compiler/sdk/go/tooling/migrate"
	"github.com/wandering-compiler/sdk/go/tooling/migrate/factory"
)

// applierFactory is the package var tests swap to inject a stub applier
// without going through DSN resolution. Production leaves it nil; Apply /
// Rollback build a real factory from W17_TARGET_<CONN> env vars. Keeping
// it a package-level seam (rather than a flag) mirrors the old
// w17migrate CLI and keeps DSNs env-only — credentials never land on a
// flag, in shell history, or in a process listing.
var applierFactory migratesdk.ApplierFor

// connTargets builds the apply-tier ConnTargets from the lock's
// connections. The apply orchestrator is lock-proto-free (public-split):
// w17ctl reads the pins from its local lockfile view and passes them in as
// plain data. Only connections with a pinned target_migration_id participate —
// an unpinned connection has never been schema-pushed, so there is nothing
// to apply.
func connTargets(lk *lockfile.Lock) []migratesdk.ConnTarget {
	// Delegated to the SDK's own view rather than mapped here. The generated
	// binary that is taking over the apply reads the same three pins off the
	// same file, and two mappings of one artefact is the shape that agrees
	// today and diverges the first time a field is added.
	view := &migratesdk.LockView{}
	for _, c := range lk.Connections {
		view.Connections = append(view.Connections, migratesdk.LockConnection{
			Name:                c.Name,
			TargetMigrationID:   c.TargetMigrationID,
			TargetContentSha256: c.TargetContentSha256,
		})
	}
	return view.ConnTargets()
}

// Fetch and apply are GONE from this client, and the removal is the point of
// the move rather than a side effect of it.
//
// Applying needs the DATABASE, and a production database is reachable only
// from its own network. So the applier has to run where the database lives —
// which is the generated storage binary, the process already there holding
// the DSNs. It mounts `migrate fetch` / `apply` / `apply --fetch`
// (sdk/go/tooling/migrate/migratecli); run it on a workstation just as well
// as on the box.
//
// Keeping a second applier here would recreate exactly the drift this move
// closes: a client on someone's machine, at whatever version they last
// installed, applying DDL generated by a console it knows nothing about.

// resolveApplier returns the applier factory for an apply / rollback run:
// the package-level test override when set, else one built from the lock's
// per-connection DSN env (resolveDSNs) with the deploy-time parallel override.
// Shared by ApplyCmd and RollbackCmd so the test-seam + env-DSN cascade lives
// in one place.
//
// W17CTL-DRYRUN — a dry run STILL needs a live applier: migrate.Plan opens each
// connection to read its AppliedHead so it can compute which pending migrations
// a real apply would run. The earlier `|| dryRun` short-circuit returned the
// (nil, in production) test override, so `migrate apply --dry-run` died with
// "migrate.Plan: ApplierFor is nil". Only the terminal Apply() is skipped, and
// the orchestrator's own DryRun branch already handles that — so resolve DSNs
// here regardless of dry-run.
func resolveApplier(lk *lockfile.Lock, parallel int) (migratesdk.ApplierFor, error) {
	if applierFactory != nil {
		return applierFactory, nil
	}
	specs, err := resolveDSNs(lk, os.Getenv)
	if err != nil {
		return nil, err
	}
	return factory.FromTargets(specs, factory.WithParallel(parallel)), nil
}

// resolveDSNs builds the per-connection DSN list from the
// W17_TARGET_<CONN_UPPER> env-var convention. A connection with a target
// pinned in the lock but no DSN is a clear error listing the connection
// name + the env var the operator should set.
//
// envLookup is a parameterised getenv so tests drive it without
// t.Setenv (production wires os.Getenv). DSNs are always env-only —
// never a flag — so credentials don't leak into shell history or process
// listings.
func resolveDSNs(lk *lockfile.Lock, envLookup func(string) string) ([]factory.TargetSpec, error) {
	var specs []factory.TargetSpec
	var missing []string
	for _, conn := range lk.Connections {
		if conn.TargetMigrationID == "" {
			continue
		}
		name := conn.Name
		dsn := envLookup(envVarName(name))
		if dsn == "" {
			missing = append(missing, name)
			continue
		}
		specs = append(specs, factory.TargetSpec{Connection: name, DSN: dsn})
	}
	if len(missing) > 0 {
		first := missing[0]
		return nil, fmt.Errorf(
			"apply: no DSN for connection(s) %s — set env var %s",
			strings.Join(missing, ", "), envVarName(first),
		)
	}
	return specs, nil
}

// envVarName turns a schema-declared connection name into the
// W17_TARGET_<CONN_UPPER> convention. Hyphens collapse to underscores so
// connection name `read-replica` resolves via `W17_TARGET_READ_REPLICA`.
//
// The rule itself lives in the SDK: the generated binary reads the same
// variables, and an operator who sets the one THIS side names while the other
// side looks for a different spelling gets "no DSN for connection" pointing at
// a variable they can see is set.
func envVarName(connection string) string {
	return migratesdk.TargetEnvVar(connection)
}
