package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// w17IgnoreHeader tops the generated w17/.gitignore. Kept as a marker so a
// re-run can tell an auto-generated file from a hand-authored one, and so
// the file explains itself to a human reading the tree.
const w17IgnoreHeader = "# w17-owned transient + local-secret paths — machine-local, never commit.\n" +
	"# Generated by w17ctl (init). Safe to edit — w17ctl only APPENDS missing\n" +
	"# lines, never rewrites yours. Scoped to the w17/ tree; the patterns are\n" +
	"# relative, so `.env` / `.secrets` also cover the per-bundle copies under\n" +
	"# w17/services/*/ (the committed *.defaults / *.example templates stay tracked)."

// w17IgnoreEntry is one ignore pattern plus the comment that documents WHY
// it is ignored — so a developer inspecting the generated w17/ tree never
// has to guess which paths are transient/secret vs. committable.
type w17IgnoreEntry struct {
	comment string
	pattern string
}

// w17IgnoreEntries is the canonical ignore set for the w17/ subtree. Every
// path w17ctl writes into w17/ that is machine-local (disposable scratch)
// or secret (never-commit key material) lives here, in one place, so the
// generated tree is self-describing. Patterns are relative to w17/ and have
// no leading slash, so they match at any depth (e.g. `.env` also ignores
// w17/services/<bundle>/.env).
var w17IgnoreEntries = []w17IgnoreEntry{
	{"Dev DB snapshots — disposable branch-scoped scratch (dev DB lifecycle).", "tmp/"},
	{"Local dev PKI (self-signed CA + server leaf) — machine-local TLS material.", "certs/dev.local/"},
	{"age secret keys — private key material, mounted at deploy, never committed.", "keys/"},
	{"Local env + secrets. The committed *.defaults / *.example templates are the\n# tracked source; the filled-in local copies below stay out of git.", ".env"},
	{"", ".env.local"},
	{"", ".secrets"},

	// ---- Compiler output -------------------------------------------------
	//
	// These are not transient or secret; they are kept out of git because a
	// pull request should show the change you made rather than the thousands
	// of lines the compiler wrote around it. On a real consuming project 92%
	// of tracked lines are codegen output (269 439 of 292 547 — deinvo,
	// 2026-09-13), and GitHub counts those files toward a PR's size and its
	// "files changed" regardless of `linguist-generated`. A diff nobody can
	// read is a review that does not happen.
	//
	// ⚠️ ANCHORED (leading slash) and ENUMERATED, never `*` with negations.
	// The two failure directions are not symmetrical: a blanket pattern
	// swallows the next AUTHORED directory somebody adds — silently,
	// discovered when a fresh clone comes back missing work — while an
	// explicit list merely leaves a newly generated directory committed until
	// this list learns about it. Noise is recoverable; loss is not. The
	// anchor keeps `/map/` from matching some `map/` nested in a bundle.
	//
	// ⛔ Three kinds of thing a generator writes STAY tracked and must never
	// be added below:
	//
	//   - STATE, not output: `proto/domains/*/w17.lock.acl.proto` and
	//     `w17.lock.events.proto` carry monotonic ids and tombstones and are
	//     derivable only from the protos AND their own previous version. Lose
	//     them and the ids renumber, so every seeded RolePermission then
	//     grants a DIFFERENT permission — silently. `w17/lock.yaml` is the
	//     same class: project id, plugin pins, signature.
	//   - What a FRESH CLONE needs before codegen can run: `w17/schema/` is
	//     applied by pipelines that never reach a console, and `w17/ci/` is
	//     the bootstrap that would otherwise have to exist to regenerate
	//     itself.
	//   - What is AUTHORED after being scaffolded once: `w17/e2e/` skeletons,
	//     `w17/languages/` catalogues, `w17/admin-custom/`, and the
	//     hand-written fixtures under `w17/fixtures/`.
}

// w17OutputIgnoreEntries is the compiler-output half of the set, kept
// separate because it is the half a project can decline — see
// [TrackGeneratedEnv].
var w17OutputIgnoreEntries = []w17IgnoreEntry{
	{"Generated service bundles — rebuilt by `w17ctl codegen`.", "/services/"},
	{"The w17-owned Go stub module (pb + grpc clients).", "/stubs/"},
	{"Vendored @w17/admin-runtime — a verbatim copy, never edited here.", "/admin-runtime/"},
	{"Generated front-end clients.", "/web-client/"},
	{"", "/js-client/"},
	{"The platform reference + project map — refreshed from the console every codegen.", "/specs/"},
	{"", "/map/"},
	{"", "/AGENTS.md"},
	{"Base rsync ignore for `w17ctl stack` remote mode — regenerated every codegen.", "/rsync.ignore"},
}

// TrackGeneratedEnv opts a project OUT of ignoring compiler output. Set it to
// "1" when the generated tree is itself the artefact under review — this
// repository's `examples/*` are golden fixtures whose regenerated diff is how
// a compiler change proves it reached anything, so ignoring them would hide
// exactly what the regen exists to show.
//
// It is a per-project decision that does not belong in the lock: the lock is
// signed and shared, while "do I review generated diffs" is a property of the
// checkout, not of the project's contract.
const TrackGeneratedEnv = "W17_TRACK_GENERATED"

// ignoreEntries returns the patterns to enforce: the machine-local + secret
// set always, plus the compiler-output set unless the project opted out.
func ignoreEntries() []w17IgnoreEntry {
	if os.Getenv(TrackGeneratedEnv) == "1" {
		return w17IgnoreEntries
	}
	return append(append([]w17IgnoreEntry(nil), w17IgnoreEntries...), w17OutputIgnoreEntries...)
}

// RefreshW17Gitignore updates an EXISTING w17/.gitignore and, unlike
// [EnsureW17Gitignore], never creates one. It is what `codegen` calls.
//
// The distinction is not cosmetic. Creating the file is `init`'s job, and
// `init` has run for every real project — so refresh-only still delivers new
// patterns everywhere they are wanted. Creating it from codegen instead
// reached trees that had deliberately gone without one: this repository's
// `examples/*`, where the root .gitignore carries `!examples/**/.env` to keep
// per-bundle `.env` files TRACKED. A nested ignore file outranks that
// negation, so a freshly generated bundle's `.env` would have stopped being
// added — silently, because git only ignores what is not already tracked.
func RefreshW17Gitignore(projectRoot string) (changed bool, err error) {
	if _, serr := os.Stat(filepath.Join(projectRoot, "w17", ".gitignore")); serr != nil {
		if os.IsNotExist(serr) {
			return false, nil // `init` owns creation
		}
		return false, fmt.Errorf("w17 gitignore: stat: %w", serr)
	}
	return EnsureW17Gitignore(projectRoot)
}

// EnsureW17Gitignore writes/updates <projectRoot>/w17/.gitignore so it
// ignores every machine-local / secret path w17ctl lays into the w17/ tree
// (snapshots, dev PKI, age keys, per-bundle .env/.secrets). It is the single
// source of truth for "what in the generated w17/ tree is transient" — init
// writes it up front so the operator never has to reverse-engineer it, and
// the snapshot / secrets paths call it too so the guarantee holds even for
// projects created before it existed.
//
// Idempotent and edit-preserving: an existing file is read, and only the
// canonical patterns not already present (exact-line match) are appended —
// hand-added rules and reorderings survive. Returns true when the file was
// created or a missing pattern was appended.
func EnsureW17Gitignore(projectRoot string) (changed bool, err error) {
	path := filepath.Join(projectRoot, "w17", ".gitignore")

	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("w17 gitignore: read: %w", err)
	}
	present := map[string]bool{}
	for _, line := range strings.Split(string(existing), "\n") {
		if p := strings.TrimSpace(line); p != "" {
			present[p] = true
		}
	}

	var missing []w17IgnoreEntry
	for _, e := range ignoreEntries() {
		if !present[e.pattern] {
			missing = append(missing, e)
		}
	}
	if len(missing) == 0 {
		return false, nil
	}

	var b strings.Builder
	b.Write(existing)
	if len(existing) == 0 {
		b.WriteString(w17IgnoreHeader)
		b.WriteByte('\n')
	} else if !strings.HasSuffix(string(existing), "\n") {
		b.WriteByte('\n')
	}
	for _, e := range missing {
		b.WriteByte('\n')
		if e.comment != "" {
			fmt.Fprintf(&b, "# %s\n", e.comment)
		}
		b.WriteString(e.pattern)
		b.WriteByte('\n')
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, fmt.Errorf("w17 gitignore: mkdir: %w", err)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return false, fmt.Errorf("w17 gitignore: write: %w", err)
	}
	return true, nil
}
