package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// w17IgnoreHeader tops the generated w17/.gitignore. Kept as a marker so a
// re-run can tell an auto-generated file from a hand-authored one, and so
// the file explains itself to a human reading the tree.
const w17IgnoreHeader = "# w17-owned transient + local-secret paths — machine-local, never commit.\n" +
	"# Generated by w17ctl (init). Safe to edit — w17ctl only APPENDS missing\n" +
	"# lines, never rewrites yours. Scoped to the w17/ tree; the patterns are\n" +
	"# relative, so `.env` / `.secrets` also cover the per-bundle copies under\n" +
	"# w17/services/*/ (the committed *.defaults / *.example templates stay tracked)."

// w17IgnoreEntry is one ignore pattern plus the comment that documents WHY
// it is ignored — so a developer inspecting the generated w17/ tree never
// has to guess which paths are transient/secret vs. committable.
type w17IgnoreEntry struct {
	comment string
	pattern string
}

// w17IgnoreEntries is the canonical ignore set for the w17/ subtree. Every
// path w17ctl writes into w17/ that is machine-local (disposable scratch)
// or secret (never-commit key material) lives here, in one place, so the
// generated tree is self-describing. Patterns are relative to w17/ and have
// no leading slash, so they match at any depth (e.g. `.env` also ignores
// w17/services/<bundle>/.env).
var w17IgnoreEntries = []w17IgnoreEntry{
	{"Dev DB snapshots — disposable branch-scoped scratch (dev DB lifecycle).", "tmp/"},
	{"Local dev PKI (self-signed CA + server leaf) — machine-local TLS material.", "certs/dev.local/"},
	{"age secret keys — private key material, mounted at deploy, never committed.", "keys/"},
	{"Local env + secrets. The committed *.defaults / *.example templates are the\n# tracked source; the filled-in local copies below stay out of git.", ".env"},
	{"", ".env.local"},
	{"", ".secrets"},
}

// EnsureW17Gitignore writes/updates <projectRoot>/w17/.gitignore so it
// ignores every machine-local / secret path w17ctl lays into the w17/ tree
// (snapshots, dev PKI, age keys, per-bundle .env/.secrets). It is the single
// source of truth for "what in the generated w17/ tree is transient" — init
// writes it up front so the operator never has to reverse-engineer it, and
// the snapshot / secrets paths call it too so the guarantee holds even for
// projects created before it existed.
//
// Idempotent and edit-preserving: an existing file is read, and only the
// canonical patterns not already present (exact-line match) are appended —
// hand-added rules and reorderings survive. Returns true when the file was
// created or a missing pattern was appended.
func EnsureW17Gitignore(projectRoot string) (changed bool, err error) {
	path := filepath.Join(projectRoot, "w17", ".gitignore")

	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("w17 gitignore: read: %w", err)
	}
	present := map[string]bool{}
	for _, line := range strings.Split(string(existing), "\n") {
		if p := strings.TrimSpace(line); p != "" {
			present[p] = true
		}
	}

	var missing []w17IgnoreEntry
	for _, e := range w17IgnoreEntries {
		if !present[e.pattern] {
			missing = append(missing, e)
		}
	}
	if len(missing) == 0 {
		return false, nil
	}

	var b strings.Builder
	b.Write(existing)
	if len(existing) == 0 {
		b.WriteString(w17IgnoreHeader)
		b.WriteByte('\n')
	} else if !strings.HasSuffix(string(existing), "\n") {
		b.WriteByte('\n')
	}
	for _, e := range missing {
		b.WriteByte('\n')
		if e.comment != "" {
			fmt.Fprintf(&b, "# %s\n", e.comment)
		}
		b.WriteString(e.pattern)
		b.WriteByte('\n')
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, fmt.Errorf("w17 gitignore: mkdir: %w", err)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return false, fmt.Errorf("w17 gitignore: write: %w", err)
	}
	return true, nil
}
